config/routes.rb
BeccArt::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :owners

  resources :guests

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

		can :read, :all
		can :create, Guest
		if user && user.admin?
			can :access, :rails_admin
			can :dashboard
			can :manage, Guest
		end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  attr_accessible :email, :email_updates, :name, :show_name, :twitter, :website

	before_save { |guest| guest.name = name.titleize }
	before_save { |guest| guest.email = email.downcase }

	VALID_NAME_REGEX = /\A[a-zA-Z][a-z]+( [a-zA-Z](\.)?([a-z]+)?)?( [a-zA-Z](\.)?([a-z]+)?)?\z/

	validates :name,
		presence: true,
		format: { with: VALID_NAME_REGEX },
		uniqueness: { case_sensitive: false }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email,
		presence: true,
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }

	VALID_WEB_REGEX = /\A(www\.)?[\w\-.]+\.[a-z]+([\w\\\-]+)?\z/i

	validates :website,
		allow_blank: true,
		format: { with: VALID_WEB_REGEX }

	validates :twitter,
		allow_blank: true,
		uniqueness: { case_sensitive: true }

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

	def admin?
		return true
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	# Change current_user to current_owner for rails_admin setup
	def current_ability
		@current_ability ||= Ability.new(current_owner)
	end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
 
  def index
    @guests = Guest.all
		@guest = Guest.new
  end

	def new
		@guest = Guest.new
	end

	def show
		if can? :manage, Guest
			@guest = Guest.find(params[:id])
		else
			flash[:error] = "You do not have access to that page"
			redirect_to guests_url
		end
	end

  def edit
		if can? :manage, Guest
    	@guest = Guest.find(params[:id])
		else
			flash[:error] = "You do not have access to that page"
			redirect_to guests_url
		end
  end

  def create
		@guests = Guest.all
    @guest = Guest.new(params[:guest])
		if @guest.save
			flash[:success] = "Thank you for signing the Guest Book"
			redirect_to guests_url
		else
			render 'index'
		end
  end

  def update
		if can? :manage, Guest
	    @guest = Guest.find(params[:id])

	    respond_to do |format|
	      if @guest.update_attributes(params[:guest])
	        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @guest.errors, status: :unprocessable_entity }
	      end
	    end
		else
			flash[:error] = "You do not have access to that page"
			redirect_to guests_url
		end
  end

  def destroy
		if can? :manage, Guest
	    @guest = Guest.find(params[:id])
	    if @guest.destroy
				flash[:success] = "Guest Signature Removed"
				redirect_to guests_url
			else
				flash.now[:error] = "Failed to Remove Guest Signature"
				render 'index'
			end
		else
			flash[:error] = "You do not have access to that page"
			redirect_to guests_url
		end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guests/_form.html.erb
<%= form_for @guest, html: { class: "well" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "John Smith" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "user@example.com" %>
		<span class="help-block">This will not be displayed</span>
  </div>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website, placeholder: "example.com" %>
  </div>
  <div class="field">
    <%= f.label :twitter %>
    <%= f.text_field :twitter, placeholder: "nyancat" %>
  </div>
  <div class="field">
		<label class="checkbox">
    	<%= f.check_box :show_name %> Show Name
		</label>
  </div>
  <div class="field">
		<label class="checkbox">
    	<%= f.check_box :email_updates %> Email Me Updates
		</label>
  </div>
  <div class="actions">
    <%= f.submit "Sign Guestbook", class: "btn btn-larg btn-success" %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<% provide(:title, "BeccArt Guestbook") %>
<div class='row'>
	<div class='span3'>
		<%= render 'form' %>
	</div>
	<div class='span6'>
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Website</th>
				<th>Twitter</th>
				<% if can? :manage, @guests%>
				<th>Show</th>
				<th>Edit</th>
				<th>Destroy</th>
				<% end %>
			</tr>

		<% @guests.each do |guest| %>
			<tr>
				<td>
					<% if guest.show_name? %>
						<%= guest.name %>
					<% else %>
						Anonymous
					<% end %>
				</td>
				<td>
					<% if not guest.website.nil? and not guest.website.empty? %>
						<%= link_to guest.website, "http://#{guest.website}" %>
					<% else %>
						---
					<% end %>
				</td>
				<td>
					<% if not guest.twitter.nil? and not guest.twitter.empty? %>
						<%= link_to "http://twitter.com/#!/#{guest.twitter}", class: "btn btn-info" do%>
							@<%= guest.twitter %>
						<% end %>
					<% else %>
						---
					<% end %>
				</td>
				<% if can? :manage, @guest %>
				<td>
					<%= link_to 'Show', guest %>
				</td>
				<td>
					<%= link_to 'Edit', edit_guest_path(guest) %>
				</td>
				<td>
					<%= link_to 'Destroy', guest, confirm: 'Are you sure?', method: :delete %>
				</td>
				<% end %>
			</tr>
		<% end %>
		</table>
	</div>
</div>

app/views/guests/new.html.erb
<% provide(:title, "Sign Guestbook") %>

<div class='span5 offset2'>
	<%= render 'form' %>
</div>

app/views/guests/show.html.erb
<% provide(:title, "BeccArt Guestbook") %>

<div class='span5 offset2'>
	<div class='row'>
		<div class='span3 offset1'>
			<h4>Name</h4>
		</div>
		<div class='span3 offset1'>
			<%= @guest.name %>
		</div>
		<div class='span3 offset1'>
			<h4>Website</h4>
		</div>
		<div class='span3 offset1'>
			<%= (@guest.website.nil? or @guest.website.empty?) ? "---" : @guest.website %>
		</div>
		<div class='span3 offset1'>
			<h4>Twitter</h4>
		</div>
		<div class='span3 offset1'>
			<%= (@guest.twitter.nil? or @guest.twitter.empty?) ? "---" : @guest.twitter %>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div>
  &copy; BeccArt 2012
  All Rights Reserved
</div>

app/views/layouts/_navigation.html.erb
<div class='helloMenu'>
	<ul class='nav nav-tabs nav-stacked'>
		<li>
			<%= link_to "Gallery", "#" %>
		</li>
		<li>
			<%= link_to "Guestbook", guests_url %>
		</li>
		<li>
			<%= link_to "Shop", "#" %>
		</li>
		<li>
			<%= link_to "Comissions", "#" %>
		</li>
		<li>
			<%= link_to "About", about_url %>
		</li>
	</ul>
</div>
<div class='helloMonster'>
	<img src='/assets/HelloMonster.jpg'></img>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content=""width=device-width, initial-scale=1.0">
  </head>
  <body>
  <div class='page hidden-phone'>
    <div class='container wrapper'>
      <div class='row'>
        <div class='content span9'>
					<h1><%= yield(:title) %></h1>
					<% flash.each do |key,value| %>
						<div class="alert alert-<%= key %>"><%= value %></div>
					<% end %>
          <%=  yield %>
        </div>
        <div class='navigation span3'>
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
    <div class='footer'>
      <%=  render 'layouts/footer' %>
    </div>
  </div>
  <div class='page visible-phone'>
    <div class='wrapper'>
      <div class='header'>
        <%= render 'layouts/navigation' %>
      </div>
      <div class='content'>
        <%= yield %>
      </div>
    </div>
    <div class='footer'>
      <%= render 'layouts/footer' %>
    </div>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About BeccArt") %>
<p>About BeccArt goes here.</p>

<!-- start slipsum code -->

<p>You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. </p>

<p>Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'? </p>

<p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee. </p>

<!-- please do not remove this line -->

<div style="display:none;">
  <a href="http://slipsum.com">lorem ipsum</a></div>

<!-- end slipsum code -->

app/views/static_pages/home.html.erb
<% provide(:title, "Welcome to BeccArt") %>
<p>
  A bunch of information goes here.
</p>

<!-- start slipsum code -->

<p>You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. </p>

<p>Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'? </p>

<p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee. </p>

<!-- please do not remove this line -->

<div style="display:none;">
  <a href="http://slipsum.com">lorem ipsum</a></div>

<!-- end slipsum code -->